[profile.default]
src = "test"
out = "out"
libs = ["lib"]
solc_version = "0.8.18"

[profile.contract_Splitter_03fd]
src = "src/Splitter_03fd/src"
libs = ["src/Splitter_03fd/lib"]

[profile.contract_Splitter_3234]
src = "src/Splitter_3234/src"
libs = ["src/Splitter_3234/lib"]
